<?php

namespace Database\Seeders;

use App\Models\Jabatan;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Membuat user awal untuk testing dan first login.
     * Setiap user diasosiasikan ke jabatan struktural via jabatan_id.
     * Foto profil dummy: simpan file potoprofildummy.jpg di
     *   storage/app/public/profile-photos/potoprofildummy.jpg
     * kemudian jalankan: php artisan storage:link
     */
    public function run(): void
    {
        $now = now();

        // Ambil jabatan IDs
        $jabatanIds = Jabatan::pluck('id', 'nama');

        // Define Module Access Groups
        $modulesPenjadwalan = [
            'dashboard',
            'penjadwalan.jadwal',
            'penjadwalan.tentatif',
            'penjadwalan.definitif',
        ];

        $modulesPersuratan = [
            'dashboard',
            'persuratan.surat-masuk',
            'persuratan.surat-keluar',
        ];

        $modulesMaster = [
            'master.pengguna',
            'master.jabatans',
            'master.unit-kerja',
            'master.indeks-surat',
        ];

        // 1. Super Admin (dibuat pertama sebagai pembuat semua user awal)
        $superAdmin = User::updateOrCreate(
            ['username' => 'superadmin'],
            [
                'name'                => 'Super Admin',
                'email'               => 'superadmin@eoffice.test',
                'password'            => Hash::make('tasik123@'),
                'plain_password'      => 'tasik123@',
                'role'                => User::ROLE_SUPERADMIN,
                'nip'                 => null,
                'jabatan_id'          => null, // SuperAdmin tidak punya jabatan
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'module_access'       => [],
                'password_changed_at' => $now,
            ]
        );

        // Set created_by Super Admin ke dirinya sendiri
        $superAdmin->update(['created_by' => $superAdmin->id]);

        // 2. User lainnya (created_by = Super Admin)
        $users = [
            [
                'name'                => 'Tata Usaha',
                'username'            => 'tatausaha',
                'email'               => 'tatausaha@eoffice.test',
                'password'            => Hash::make('tatausaha123@'),
                'plain_password'      => 'tatausaha123@',
                'role'                => User::ROLE_TU,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Tata Usaha'] ?? null,
                'jenis_kelamin'       => 'P',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => array_merge(
                    ['dashboard'],
                    $modulesMaster,
                    [
                        'master.jenis-surat',
                        'master.sifat-surat',
                    ],
                    $modulesPersuratan,
                    $modulesPenjadwalan,
                    ['penjadwalan.history']
                ),
            ],
            [
                'name'                => 'Bupati',
                'username'            => 'bupati',
                'email'               => 'bupati@eoffice.test',
                'password'            => Hash::make('bupati123@'),
                'plain_password'      => 'bupati123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Bupati'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => array_merge(
                    $modulesPersuratan,
                    $modulesPenjadwalan
                ),
            ],
            [
                'name'                => 'Wakil Bupati',
                'username'            => 'wakilbupati',
                'email'               => 'wakilbupati@eoffice.test',
                'password'            => Hash::make('wakilbupati123@'),
                'plain_password'      => 'wakilbupati123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Wakil Bupati'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => array_merge(
                    $modulesPersuratan,
                    $modulesPenjadwalan
                ),
            ],
            [
                'name'                => 'Sekretaris Daerah',
                'username'            => 'sekda',
                'email'               => 'sekda@eoffice.test',
                'password'            => Hash::make('sekda123@'),
                'plain_password'      => 'sekda123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Sekretaris Daerah'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Asda 1',
                'username'            => 'asda1',
                'email'               => 'asda1@eoffice.test',
                'password'            => Hash::make('asda1123@'),
                'plain_password'      => 'asda1123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Asisten Daerah I'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Asda 2',
                'username'            => 'asda2',
                'email'               => 'asda2@eoffice.test',
                'password'            => Hash::make('asda2123@'),
                'plain_password'      => 'asda2123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Asisten Daerah II'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Asda 3',
                'username'            => 'asda3',
                'email'               => 'asda3@eoffice.test',
                'password'            => Hash::make('asda3123@'),
                'plain_password'      => 'asda3123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Asisten Daerah III'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            // === Staff Ahli ===
            [
                'name'                => 'Staff Ahli 1',
                'username'            => 'staffahli1',
                'email'               => 'staffahli1@eoffice.test',
                'password'            => Hash::make('staffahli1123@'),
                'plain_password'      => 'staffahli1123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Staff Ahli I'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Staff Ahli 2',
                'username'            => 'staffahli2',
                'email'               => 'staffahli2@eoffice.test',
                'password'            => Hash::make('staffahli2123@'),
                'plain_password'      => 'staffahli2123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Staff Ahli II'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Staff Ahli 3',
                'username'            => 'staffahli3',
                'email'               => 'staffahli3@eoffice.test',
                'password'            => Hash::make('staffahli3123@'),
                'plain_password'      => 'staffahli3123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Staff Ahli III'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            // === Kabag (Kepala Bagian) ===
            [
                'name'                => 'Kabag Kesejahteraan Rakyat',
                'username'            => 'kabagkesra',
                'email'               => 'kabagkesra@eoffice.test',
                'password'            => Hash::make('kabagkesra123@'),
                'plain_password'      => 'kabagkesra123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kabag Organisasi',
                'username'            => 'kabagorganisasi',
                'email'               => 'kabagorganisasi@eoffice.test',
                'password'            => Hash::make('kabagorganisasi123@'),
                'plain_password'      => 'kabagorganisasi123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kabag Umum',
                'username'            => 'kabagumum',
                'email'               => 'kabagumum@eoffice.test',
                'password'            => Hash::make('kabagumum123@'),
                'plain_password'      => 'kabagumum123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kabag Hukum',
                'username'            => 'kabaghukum',
                'email'               => 'kabaghukum@eoffice.test',
                'password'            => Hash::make('kabaghukum123@'),
                'plain_password'      => 'kabaghukum123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kabag Ekonomi Pembangunan',
                'username'            => 'kabagekbang',
                'email'               => 'kabagekbang@eoffice.test',
                'password'            => Hash::make('kabagekbang123@'),
                'plain_password'      => 'kabagekbang123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kabag Barang & Jasa',
                'username'            => 'kabagbarjas',
                'email'               => 'kabagbarjas@eoffice.test',
                'password'            => Hash::make('kabagbarjas123@'),
                'plain_password'      => 'kabagbarjas123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kabag Tata Pemerintahan',
                'username'            => 'kabagtapem',
                'email'               => 'kabagtapem@eoffice.test',
                'password'            => Hash::make('kabagtapem123@'),
                'plain_password'      => 'kabagtapem123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kabag Prokompim',
                'username'            => 'kabagprokompim',
                'email'               => 'kabagprokompim@eoffice.test',
                'password'            => Hash::make('kabagprokompim123@'),
                'plain_password'      => 'kabagprokompim123@',
                'role'                => User::ROLE_USER,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Bagian'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            // === Kepala Dinas (OPD) ===
            [
                'name'                => 'Kepala Dinas Kesehatan',
                'username'            => 'dinkes',
                'email'               => 'dinkes@eoffice.test',
                'password'            => Hash::make('dinkes123@'),
                'plain_password'      => 'dinkes123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala RSUD KHZ Mustafa',
                'username'            => 'rsudkhzmustafa',
                'email'               => 'rsudkhzmustafa@eoffice.test',
                'password'            => Hash::make('rsudkhzmustafa123@'),
                'plain_password'      => 'rsudkhzmustafa123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala RSUD Tani Nelayan',
                'username'            => 'rsudtaninelayan',
                'email'               => 'rsudtaninelayan@eoffice.test',
                'password'            => Hash::make('rsudtaninelayan123@'),
                'plain_password'      => 'rsudtaninelayan123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dinas Pendidikan',
                'username'            => 'disdik',
                'email'               => 'disdik@eoffice.test',
                'password'            => Hash::make('disdik123@'),
                'plain_password'      => 'disdik123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dinas Sosial',
                'username'            => 'dinsos',
                'email'               => 'dinsos@eoffice.test',
                'password'            => Hash::make('dinsos123@'),
                'plain_password'      => 'dinsos123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dinas PUTRPRKPLH',
                'username'            => 'putrprkplh',
                'email'               => 'putrprkplh@eoffice.test',
                'password'            => Hash::make('putrprkplh123@'),
                'plain_password'      => 'putrprkplh123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Satpol PP',
                'username'            => 'satpolpp',
                'email'               => 'satpolpp@eoffice.test',
                'password'            => Hash::make('satpolpp123@'),
                'plain_password'      => 'satpolpp123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala BPBD',
                'username'            => 'bpbd',
                'email'               => 'bpbd@eoffice.test',
                'password'            => Hash::make('bpbd123@'),
                'plain_password'      => 'bpbd123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dinas Kopukmindag',
                'username'            => 'kopukmindag',
                'email'               => 'kopukmindag@eoffice.test',
                'password'            => Hash::make('kopukmindag123@'),
                'plain_password'      => 'kopukmindag123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dinas Pertanian',
                'username'            => 'pertanian',
                'email'               => 'pertanian@eoffice.test',
                'password'            => Hash::make('pertanian123@'),
                'plain_password'      => 'pertanian123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dinas PMPTSP',
                'username'            => 'pmptsp',
                'email'               => 'pmptsp@eoffice.test',
                'password'            => Hash::make('pmptsp123@'),
                'plain_password'      => 'pmptsp123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dinas PMD',
                'username'            => 'pmd',
                'email'               => 'pmd@eoffice.test',
                'password'            => Hash::make('pmd123@'),
                'plain_password'      => 'pmd123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Dishubkominfo',
                'username'            => 'dishubkominfo',
                'email'               => 'dishubkominfo@eoffice.test',
                'password'            => Hash::make('dishubkominfo123@'),
                'plain_password'      => 'dishubkominfo123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Disdukcapil',
                'username'            => 'disdukcapil',
                'email'               => 'disdukcapil@eoffice.test',
                'password'            => Hash::make('disdukcapil123@'),
                'plain_password'      => 'disdukcapil123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Disparbudpora',
                'username'            => 'disparbudpora',
                'email'               => 'disparbudpora@eoffice.test',
                'password'            => Hash::make('disparbudpora123@'),
                'plain_password'      => 'disparbudpora123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Kesbangpol',
                'username'            => 'kesbangpol',
                'email'               => 'kesbangpol@eoffice.test',
                'password'            => Hash::make('kesbangpol123@'),
                'plain_password'      => 'kesbangpol123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Inspektur',
                'username'            => 'inspektorat',
                'email'               => 'inspektorat@eoffice.test',
                'password'            => Hash::make('inspektorat123@'),
                'plain_password'      => 'inspektorat123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala BKPSDM',
                'username'            => 'bkpsdm',
                'email'               => 'bkpsdm@eoffice.test',
                'password'            => Hash::make('bkpsdm123@'),
                'plain_password'      => 'bkpsdm123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala BPKPD',
                'username'            => 'bpkpd',
                'email'               => 'bpkpd@eoffice.test',
                'password'            => Hash::make('bpkpd123@'),
                'plain_password'      => 'bpkpd123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Sekretaris Daerah (Setda)',
                'username'            => 'setdaopd',
                'email'               => 'setdaopd@eoffice.test',
                'password'            => Hash::make('setdaopd123@'),
                'plain_password'      => 'setdaopd123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Sekretaris DPRD',
                'username'            => 'sekretariatdprd',
                'email'               => 'sekretariatdprd@eoffice.test',
                'password'            => Hash::make('sekretariatdprd123@'),
                'plain_password'      => 'sekretariatdprd123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
            [
                'name'                => 'Kepala Bappelitbangda',
                'username'            => 'bappelitbangda',
                'email'               => 'bappelitbangda@eoffice.test',
                'password'            => Hash::make('bappelitbangda123@'),
                'plain_password'      => 'bappelitbangda123@',
                'role'                => User::ROLE_PEJABAT,
                'nip'                 => null,
                'jabatan_id'          => $jabatanIds['Kepala Dinas'] ?? null,
                'jenis_kelamin'       => 'L',
                'foto'                => 'profile-photos/potoprofildummy.jpg',
                'created_by'          => $superAdmin->id,
                'password_changed_at' => $now,
                'module_access'       => $modulesPersuratan,
            ],
        ];

        foreach ($users as $userData) {
            User::updateOrCreate(
                ['username' => $userData['username']],
                $userData
            );
        }

        $this->command->info('Berhasil membuat/memperbarui ' . (count($users) + 1) . ' user.');
        $this->command->info('Login default: superadmin / tasik123@');
    }
}
