<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WilayahKabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Delete existing data
        DB::table('wilayah_kabupaten')->delete();

        $data = [
            ['provinsi_kode' => '11', 'kode' => '01', 'nama' => 'Kabupaten Aceh Selatan'],
            ['provinsi_kode' => '11', 'kode' => '02', 'nama' => 'Kabupaten Aceh Tenggara'],
            ['provinsi_kode' => '11', 'kode' => '03', 'nama' => 'Kabupaten Aceh Timur'],
            ['provinsi_kode' => '11', 'kode' => '04', 'nama' => 'Kabupaten Aceh Tengah'],
            ['provinsi_kode' => '11', 'kode' => '05', 'nama' => 'Kabupaten Aceh Barat'],
            ['provinsi_kode' => '11', 'kode' => '06', 'nama' => 'Kabupaten Aceh Besar'],
            ['provinsi_kode' => '11', 'kode' => '07', 'nama' => 'Kabupaten Pidie'],
            ['provinsi_kode' => '11', 'kode' => '08', 'nama' => 'Kabupaten Aceh Utara'],
            ['provinsi_kode' => '11', 'kode' => '09', 'nama' => 'Kabupaten Simeulue'],
            ['provinsi_kode' => '11', 'kode' => '10', 'nama' => 'Kabupaten Aceh Singkil'],
            ['provinsi_kode' => '11', 'kode' => '11', 'nama' => 'Kabupaten Bireuen'],
            ['provinsi_kode' => '11', 'kode' => '12', 'nama' => 'Kabupaten Aceh Barat Daya'],
            ['provinsi_kode' => '11', 'kode' => '13', 'nama' => 'Kabupaten Gayo Lues'],
            ['provinsi_kode' => '11', 'kode' => '14', 'nama' => 'Kabupaten Aceh Jaya'],
            ['provinsi_kode' => '11', 'kode' => '15', 'nama' => 'Kabupaten Nagan Raya'],
            ['provinsi_kode' => '11', 'kode' => '16', 'nama' => 'Kabupaten Aceh Tamiang'],
            ['provinsi_kode' => '11', 'kode' => '17', 'nama' => 'Kabupaten Bener Meriah'],
            ['provinsi_kode' => '11', 'kode' => '18', 'nama' => 'Kabupaten Pidie Jaya'],
            ['provinsi_kode' => '11', 'kode' => '71', 'nama' => 'Kota Banda Aceh'],
            ['provinsi_kode' => '11', 'kode' => '72', 'nama' => 'Kota Sabang'],
            ['provinsi_kode' => '11', 'kode' => '73', 'nama' => 'Kota Lhokseumawe'],
            ['provinsi_kode' => '11', 'kode' => '74', 'nama' => 'Kota Langsa'],
            ['provinsi_kode' => '11', 'kode' => '75', 'nama' => 'Kota Subulussalam'],
            ['provinsi_kode' => '12', 'kode' => '01', 'nama' => 'Kabupaten Tapanuli Tengah'],
            ['provinsi_kode' => '12', 'kode' => '02', 'nama' => 'Kabupaten Tapanuli Utara'],
            ['provinsi_kode' => '12', 'kode' => '03', 'nama' => 'Kabupaten Tapanuli Selatan'],
            ['provinsi_kode' => '12', 'kode' => '04', 'nama' => 'Kabupaten Nias'],
            ['provinsi_kode' => '12', 'kode' => '05', 'nama' => 'Kabupaten Langkat'],
            ['provinsi_kode' => '12', 'kode' => '06', 'nama' => 'Kabupaten Karo'],
            ['provinsi_kode' => '12', 'kode' => '07', 'nama' => 'Kabupaten Deli Serdang'],
            ['provinsi_kode' => '12', 'kode' => '08', 'nama' => 'Kabupaten Simalungun'],
            ['provinsi_kode' => '12', 'kode' => '09', 'nama' => 'Kabupaten Asahan'],
            ['provinsi_kode' => '12', 'kode' => '10', 'nama' => 'Kabupaten Labuhanbatu'],
            ['provinsi_kode' => '12', 'kode' => '11', 'nama' => 'Kabupaten Dairi'],
            ['provinsi_kode' => '12', 'kode' => '12', 'nama' => 'Kabupaten Toba'],
            ['provinsi_kode' => '12', 'kode' => '13', 'nama' => 'Kabupaten Mandailing Natal'],
            ['provinsi_kode' => '12', 'kode' => '14', 'nama' => 'Kabupaten Nias Selatan'],
            ['provinsi_kode' => '12', 'kode' => '15', 'nama' => 'Kabupaten Pakpak Bharat'],
            ['provinsi_kode' => '12', 'kode' => '16', 'nama' => 'Kabupaten Humbang Hasundutan'],
            ['provinsi_kode' => '12', 'kode' => '17', 'nama' => 'Kabupaten Samosir'],
            ['provinsi_kode' => '12', 'kode' => '18', 'nama' => 'Kabupaten Serdang Bedagai'],
            ['provinsi_kode' => '12', 'kode' => '19', 'nama' => 'Kabupaten Batu Bara'],
            ['provinsi_kode' => '12', 'kode' => '20', 'nama' => 'Kabupaten Padang Lawas Utara'],
            ['provinsi_kode' => '12', 'kode' => '21', 'nama' => 'Kabupaten Padang Lawas'],
            ['provinsi_kode' => '12', 'kode' => '22', 'nama' => 'Kabupaten Labuhanbatu Selatan'],
            ['provinsi_kode' => '12', 'kode' => '23', 'nama' => 'Kabupaten Labuhanbatu Utara'],
            ['provinsi_kode' => '12', 'kode' => '24', 'nama' => 'Kabupaten Nias Utara'],
            ['provinsi_kode' => '12', 'kode' => '25', 'nama' => 'Kabupaten Nias Barat'],
            ['provinsi_kode' => '12', 'kode' => '71', 'nama' => 'Kota Medan'],
            ['provinsi_kode' => '12', 'kode' => '72', 'nama' => 'Kota Pematangsiantar'],
            ['provinsi_kode' => '12', 'kode' => '73', 'nama' => 'Kota Sibolga'],
            ['provinsi_kode' => '12', 'kode' => '74', 'nama' => 'Kota Tanjungbalai'],
            ['provinsi_kode' => '12', 'kode' => '75', 'nama' => 'Kota Binjai'],
            ['provinsi_kode' => '12', 'kode' => '76', 'nama' => 'Kota Tebing Tinggi'],
            ['provinsi_kode' => '12', 'kode' => '77', 'nama' => 'Kota Padangsidimpuan'],
            ['provinsi_kode' => '12', 'kode' => '78', 'nama' => 'Kota Gunungsitoli'],
            ['provinsi_kode' => '13', 'kode' => '01', 'nama' => 'Kabupaten Pesisir Selatan'],
            ['provinsi_kode' => '13', 'kode' => '02', 'nama' => 'Kabupaten Solok'],
            ['provinsi_kode' => '13', 'kode' => '03', 'nama' => 'Kabupaten Sijunjung'],
            ['provinsi_kode' => '13', 'kode' => '04', 'nama' => 'Kabupaten Tanah Datar'],
            ['provinsi_kode' => '13', 'kode' => '05', 'nama' => 'Kabupaten Padang Pariaman'],
            ['provinsi_kode' => '13', 'kode' => '06', 'nama' => 'Kabupaten Agam'],
            ['provinsi_kode' => '13', 'kode' => '07', 'nama' => 'Kabupaten Lima Puluh Kota'],
            ['provinsi_kode' => '13', 'kode' => '08', 'nama' => 'Kabupaten Pasaman'],
            ['provinsi_kode' => '13', 'kode' => '09', 'nama' => 'Kabupaten Kepulauan Mentawai'],
            ['provinsi_kode' => '13', 'kode' => '10', 'nama' => 'Kabupaten Dharmasraya'],
            ['provinsi_kode' => '13', 'kode' => '11', 'nama' => 'Kabupaten Solok Selatan'],
            ['provinsi_kode' => '13', 'kode' => '12', 'nama' => 'Kabupaten Pasaman Barat'],
            ['provinsi_kode' => '13', 'kode' => '71', 'nama' => 'Kota Padang'],
            ['provinsi_kode' => '13', 'kode' => '72', 'nama' => 'Kota Solok'],
            ['provinsi_kode' => '13', 'kode' => '73', 'nama' => 'Kota Sawahlunto'],
            ['provinsi_kode' => '13', 'kode' => '74', 'nama' => 'Kota Padang Panjang'],
            ['provinsi_kode' => '13', 'kode' => '75', 'nama' => 'Kota Bukittinggi'],
            ['provinsi_kode' => '13', 'kode' => '76', 'nama' => 'Kota Payakumbuh'],
            ['provinsi_kode' => '13', 'kode' => '77', 'nama' => 'Kota Pariaman'],
            ['provinsi_kode' => '14', 'kode' => '01', 'nama' => 'Kabupaten Kampar'],
            ['provinsi_kode' => '14', 'kode' => '02', 'nama' => 'Kabupaten Indragiri Hulu'],
            ['provinsi_kode' => '14', 'kode' => '03', 'nama' => 'Kabupaten Bengkalis'],
            ['provinsi_kode' => '14', 'kode' => '04', 'nama' => 'Kabupaten Indragiri Hilir'],
            ['provinsi_kode' => '14', 'kode' => '05', 'nama' => 'Kabupaten Pelalawan'],
            ['provinsi_kode' => '14', 'kode' => '06', 'nama' => 'Kabupaten Rokan Hulu'],
            ['provinsi_kode' => '14', 'kode' => '07', 'nama' => 'Kabupaten Rokan Hilir'],
            ['provinsi_kode' => '14', 'kode' => '08', 'nama' => 'Kabupaten Siak'],
            ['provinsi_kode' => '14', 'kode' => '09', 'nama' => 'Kabupaten Kuantan Singingi'],
            ['provinsi_kode' => '14', 'kode' => '10', 'nama' => 'Kabupaten Kepulauan Meranti'],
            ['provinsi_kode' => '14', 'kode' => '71', 'nama' => 'Kota Pekanbaru'],
            ['provinsi_kode' => '14', 'kode' => '72', 'nama' => 'Kota Dumai'],
            ['provinsi_kode' => '15', 'kode' => '01', 'nama' => 'Kabupaten Kerinci'],
            ['provinsi_kode' => '15', 'kode' => '02', 'nama' => 'Kabupaten Merangin'],
            ['provinsi_kode' => '15', 'kode' => '03', 'nama' => 'Kabupaten Sarolangun'],
            ['provinsi_kode' => '15', 'kode' => '04', 'nama' => 'Kabupaten Batanghari'],
            ['provinsi_kode' => '15', 'kode' => '05', 'nama' => 'Kabupaten Muaro Jambi'],
            ['provinsi_kode' => '15', 'kode' => '06', 'nama' => 'Kabupaten Tanjung Jabung Barat'],
            ['provinsi_kode' => '15', 'kode' => '07', 'nama' => 'Kabupaten Tanjung Jabung Timur'],
            ['provinsi_kode' => '15', 'kode' => '08', 'nama' => 'Kabupaten Bungo'],
            ['provinsi_kode' => '15', 'kode' => '09', 'nama' => 'Kabupaten Tebo'],
            ['provinsi_kode' => '15', 'kode' => '71', 'nama' => 'Kota Jambi'],
            ['provinsi_kode' => '15', 'kode' => '72', 'nama' => 'Kota Sungai Penuh'],
            ['provinsi_kode' => '16', 'kode' => '01', 'nama' => 'Kabupaten Ogan Komering Ulu'],
            ['provinsi_kode' => '16', 'kode' => '02', 'nama' => 'Kabupaten Ogan Komering Ilir'],
            ['provinsi_kode' => '16', 'kode' => '03', 'nama' => 'Kabupaten Muara Enim'],
            ['provinsi_kode' => '16', 'kode' => '04', 'nama' => 'Kabupaten Lahat'],
            ['provinsi_kode' => '16', 'kode' => '05', 'nama' => 'Kabupaten Musi Rawas'],
            ['provinsi_kode' => '16', 'kode' => '06', 'nama' => 'Kabupaten Musi Banyuasin'],
            ['provinsi_kode' => '16', 'kode' => '07', 'nama' => 'Kabupaten Banyuasin'],
            ['provinsi_kode' => '16', 'kode' => '08', 'nama' => 'Kabupaten Ogan Komering Ulu Timur'],
            ['provinsi_kode' => '16', 'kode' => '09', 'nama' => 'Kabupaten Ogan Komering Ulu Selatan'],
            ['provinsi_kode' => '16', 'kode' => '10', 'nama' => 'Kabupaten Ogan Ilir'],
            ['provinsi_kode' => '16', 'kode' => '11', 'nama' => 'Kabupaten Empat Lawang'],
            ['provinsi_kode' => '16', 'kode' => '12', 'nama' => 'Kabupaten Penukal Abab Lematang Ilir'],
            ['provinsi_kode' => '16', 'kode' => '13', 'nama' => 'Kabupaten Musi Rawas Utara'],
            ['provinsi_kode' => '16', 'kode' => '71', 'nama' => 'Kota Palembang'],
            ['provinsi_kode' => '16', 'kode' => '72', 'nama' => 'Kota Pagar Alam'],
            ['provinsi_kode' => '16', 'kode' => '73', 'nama' => 'Kota Lubuk Linggau'],
            ['provinsi_kode' => '16', 'kode' => '74', 'nama' => 'Kota Prabumulih'],
            ['provinsi_kode' => '17', 'kode' => '01', 'nama' => 'Kabupaten Bengkulu Selatan'],
            ['provinsi_kode' => '17', 'kode' => '02', 'nama' => 'Kabupaten Rejang Lebong'],
            ['provinsi_kode' => '17', 'kode' => '03', 'nama' => 'Kabupaten Bengkulu Utara'],
            ['provinsi_kode' => '17', 'kode' => '04', 'nama' => 'Kabupaten Kaur'],
            ['provinsi_kode' => '17', 'kode' => '05', 'nama' => 'Kabupaten Seluma'],
            ['provinsi_kode' => '17', 'kode' => '06', 'nama' => 'Kabupaten Mukomuko'],
            ['provinsi_kode' => '17', 'kode' => '07', 'nama' => 'Kabupaten Lebong'],
            ['provinsi_kode' => '17', 'kode' => '08', 'nama' => 'Kabupaten Kepahiang'],
            ['provinsi_kode' => '17', 'kode' => '09', 'nama' => 'Kabupaten Bengkulu Tengah'],
            ['provinsi_kode' => '17', 'kode' => '71', 'nama' => 'Kota Bengkulu'],
            ['provinsi_kode' => '18', 'kode' => '01', 'nama' => 'Kabupaten Lampung Selatan'],
            ['provinsi_kode' => '18', 'kode' => '02', 'nama' => 'Kabupaten Lampung Tengah'],
            ['provinsi_kode' => '18', 'kode' => '03', 'nama' => 'Kabupaten Lampung Utara'],
            ['provinsi_kode' => '18', 'kode' => '04', 'nama' => 'Kabupaten Lampung Barat'],
            ['provinsi_kode' => '18', 'kode' => '05', 'nama' => 'Kabupaten Tulang Bawang'],
            ['provinsi_kode' => '18', 'kode' => '06', 'nama' => 'Kabupaten Tanggamus'],
            ['provinsi_kode' => '18', 'kode' => '07', 'nama' => 'Kabupaten Lampung Timur'],
            ['provinsi_kode' => '18', 'kode' => '08', 'nama' => 'Kabupaten Way Kanan'],
            ['provinsi_kode' => '18', 'kode' => '09', 'nama' => 'Kabupaten Pesawaran'],
            ['provinsi_kode' => '18', 'kode' => '10', 'nama' => 'Kabupaten Pringsewu'],
            ['provinsi_kode' => '18', 'kode' => '11', 'nama' => 'Kabupaten Mesuji'],
            ['provinsi_kode' => '18', 'kode' => '12', 'nama' => 'Kabupaten Tulang Bawang Barat'],
            ['provinsi_kode' => '18', 'kode' => '13', 'nama' => 'Kabupaten Pesisir Barat'],
            ['provinsi_kode' => '18', 'kode' => '71', 'nama' => 'Kota Bandar Lampung'],
            ['provinsi_kode' => '18', 'kode' => '72', 'nama' => 'Kota Metro'],
            ['provinsi_kode' => '19', 'kode' => '01', 'nama' => 'Kabupaten Bangka'],
            ['provinsi_kode' => '19', 'kode' => '02', 'nama' => 'Kabupaten Belitung'],
            ['provinsi_kode' => '19', 'kode' => '03', 'nama' => 'Kabupaten Bangka Selatan'],
            ['provinsi_kode' => '19', 'kode' => '04', 'nama' => 'Kabupaten Bangka Tengah'],
            ['provinsi_kode' => '19', 'kode' => '05', 'nama' => 'Kabupaten Bangka Barat'],
            ['provinsi_kode' => '19', 'kode' => '06', 'nama' => 'Kabupaten Belitung Timur'],
            ['provinsi_kode' => '19', 'kode' => '71', 'nama' => 'Kota Pangkal Pinang'],
            ['provinsi_kode' => '21', 'kode' => '01', 'nama' => 'Kabupaten Bintan'],
            ['provinsi_kode' => '21', 'kode' => '02', 'nama' => 'Kabupaten Karimun'],
            ['provinsi_kode' => '21', 'kode' => '03', 'nama' => 'Kabupaten Natuna'],
            ['provinsi_kode' => '21', 'kode' => '04', 'nama' => 'Kabupaten Lingga'],
            ['provinsi_kode' => '21', 'kode' => '05', 'nama' => 'Kabupaten Kepulauan Anambas'],
            ['provinsi_kode' => '21', 'kode' => '71', 'nama' => 'Kota Batam'],
            ['provinsi_kode' => '21', 'kode' => '72', 'nama' => 'Kota Tanjung Pinang'],
            ['provinsi_kode' => '31', 'kode' => '01', 'nama' => 'Kabupaten Administrasi Kepulauan Seribu'],
            ['provinsi_kode' => '31', 'kode' => '71', 'nama' => 'Kota Administrasi Jakarta Pusat'],
            ['provinsi_kode' => '31', 'kode' => '72', 'nama' => 'Kota Administrasi Jakarta Utara '],
            ['provinsi_kode' => '31', 'kode' => '73', 'nama' => 'Kota Administrasi Jakarta Barat'],
            ['provinsi_kode' => '31', 'kode' => '74', 'nama' => 'Kota Administrasi Jakarta Selatan'],
            ['provinsi_kode' => '31', 'kode' => '75', 'nama' => 'Kota Administrasi Jakarta Timur'],
            ['provinsi_kode' => '32', 'kode' => '01', 'nama' => 'Kabupaten Bogor'],
            ['provinsi_kode' => '32', 'kode' => '02', 'nama' => 'Kabupaten Sukabumi'],
            ['provinsi_kode' => '32', 'kode' => '03', 'nama' => 'Kabupaten Cianjur'],
            ['provinsi_kode' => '32', 'kode' => '04', 'nama' => 'Kabupaten Bandung'],
            ['provinsi_kode' => '32', 'kode' => '05', 'nama' => 'Kabupaten Garut'],
            ['provinsi_kode' => '32', 'kode' => '06', 'nama' => 'Kabupaten Tasikmalaya'],
            ['provinsi_kode' => '32', 'kode' => '07', 'nama' => 'Kabupaten Ciamis'],
            ['provinsi_kode' => '32', 'kode' => '08', 'nama' => 'Kabupaten Kuningan'],
            ['provinsi_kode' => '32', 'kode' => '09', 'nama' => 'Kabupaten Cirebon'],
            ['provinsi_kode' => '32', 'kode' => '10', 'nama' => 'Kabupaten Majalengka'],
            ['provinsi_kode' => '32', 'kode' => '11', 'nama' => 'Kabupaten Sumedang'],
            ['provinsi_kode' => '32', 'kode' => '12', 'nama' => 'Kabupaten Indramayu'],
            ['provinsi_kode' => '32', 'kode' => '13', 'nama' => 'Kabupaten Subang'],
            ['provinsi_kode' => '32', 'kode' => '14', 'nama' => 'Kabupaten Purwakarta'],
            ['provinsi_kode' => '32', 'kode' => '15', 'nama' => 'Kabupaten Karawang'],
            ['provinsi_kode' => '32', 'kode' => '16', 'nama' => 'Kabupaten Bekasi'],
            ['provinsi_kode' => '32', 'kode' => '17', 'nama' => 'Kabupaten Bandung Barat'],
            ['provinsi_kode' => '32', 'kode' => '18', 'nama' => 'Kabupaten Pangandaran'],
            ['provinsi_kode' => '32', 'kode' => '71', 'nama' => 'Kota Bogor'],
            ['provinsi_kode' => '32', 'kode' => '72', 'nama' => 'Kota Sukabumi'],
            ['provinsi_kode' => '32', 'kode' => '73', 'nama' => 'Kota Bandung'],
            ['provinsi_kode' => '32', 'kode' => '74', 'nama' => 'Kota Cirebon'],
            ['provinsi_kode' => '32', 'kode' => '75', 'nama' => 'Kota Bekasi'],
            ['provinsi_kode' => '32', 'kode' => '76', 'nama' => 'Kota Depok'],
            ['provinsi_kode' => '32', 'kode' => '77', 'nama' => 'Kota Cimahi'],
            ['provinsi_kode' => '32', 'kode' => '78', 'nama' => 'Kota Tasikmalaya'],
            ['provinsi_kode' => '32', 'kode' => '79', 'nama' => 'Kota Banjar'],
            ['provinsi_kode' => '33', 'kode' => '01', 'nama' => 'Kabupaten Cilacap'],
            ['provinsi_kode' => '33', 'kode' => '02', 'nama' => 'Kabupaten Banyumas'],
            ['provinsi_kode' => '33', 'kode' => '03', 'nama' => 'Kabupaten Purbalingga'],
            ['provinsi_kode' => '33', 'kode' => '04', 'nama' => 'Kabupaten Banjarnegara'],
            ['provinsi_kode' => '33', 'kode' => '05', 'nama' => 'Kabupaten Kebumen'],
            ['provinsi_kode' => '33', 'kode' => '06', 'nama' => 'Kabupaten Purworejo'],
            ['provinsi_kode' => '33', 'kode' => '07', 'nama' => 'Kabupaten Wonosobo'],
            ['provinsi_kode' => '33', 'kode' => '08', 'nama' => 'Kabupaten Magelang'],
            ['provinsi_kode' => '33', 'kode' => '09', 'nama' => 'Kabupaten Boyolali'],
            ['provinsi_kode' => '33', 'kode' => '10', 'nama' => 'Kabupaten Klaten'],
            ['provinsi_kode' => '33', 'kode' => '11', 'nama' => 'Kabupaten Sukoharjo'],
            ['provinsi_kode' => '33', 'kode' => '12', 'nama' => 'Kabupaten Wonogiri'],
            ['provinsi_kode' => '33', 'kode' => '13', 'nama' => 'Kabupaten Karanganyar'],
            ['provinsi_kode' => '33', 'kode' => '14', 'nama' => 'Kabupaten Sragen'],
            ['provinsi_kode' => '33', 'kode' => '15', 'nama' => 'Kabupaten Grobogan'],
            ['provinsi_kode' => '33', 'kode' => '16', 'nama' => 'Kabupaten Blora'],
            ['provinsi_kode' => '33', 'kode' => '17', 'nama' => 'Kabupaten Rembang'],
            ['provinsi_kode' => '33', 'kode' => '18', 'nama' => 'Kabupaten Pati'],
            ['provinsi_kode' => '33', 'kode' => '19', 'nama' => 'Kabupaten Kudus'],
            ['provinsi_kode' => '33', 'kode' => '20', 'nama' => 'Kabupaten Jepara'],
            ['provinsi_kode' => '33', 'kode' => '21', 'nama' => 'Kabupaten Demak'],
            ['provinsi_kode' => '33', 'kode' => '22', 'nama' => 'Kabupaten Semarang'],
            ['provinsi_kode' => '33', 'kode' => '23', 'nama' => 'Kabupaten Temanggung'],
            ['provinsi_kode' => '33', 'kode' => '24', 'nama' => 'Kabupaten Kendal'],
            ['provinsi_kode' => '33', 'kode' => '25', 'nama' => 'Kabupaten Batang'],
            ['provinsi_kode' => '33', 'kode' => '26', 'nama' => 'Kabupaten Pekalongan'],
            ['provinsi_kode' => '33', 'kode' => '27', 'nama' => 'Kabupaten Pemalang'],
            ['provinsi_kode' => '33', 'kode' => '28', 'nama' => 'Kabupaten Tegal'],
            ['provinsi_kode' => '33', 'kode' => '29', 'nama' => 'Kabupaten Brebes'],
            ['provinsi_kode' => '33', 'kode' => '71', 'nama' => 'Kota Magelang'],
            ['provinsi_kode' => '33', 'kode' => '72', 'nama' => 'Kota Surakarta'],
            ['provinsi_kode' => '33', 'kode' => '73', 'nama' => 'Kota Salatiga'],
            ['provinsi_kode' => '33', 'kode' => '74', 'nama' => 'Kota Semarang'],
            ['provinsi_kode' => '33', 'kode' => '75', 'nama' => 'Kota Pekalongan'],
            ['provinsi_kode' => '33', 'kode' => '76', 'nama' => 'Kota Tegal'],
            ['provinsi_kode' => '34', 'kode' => '01', 'nama' => 'Kabupaten Kulon Progo'],
            ['provinsi_kode' => '34', 'kode' => '02', 'nama' => 'Kabupaten Bantul'],
            ['provinsi_kode' => '34', 'kode' => '03', 'nama' => 'Kabupaten Gunungkidul'],
            ['provinsi_kode' => '34', 'kode' => '04', 'nama' => 'Kabupaten Sleman'],
            ['provinsi_kode' => '34', 'kode' => '71', 'nama' => 'Kota Yogyakarta'],
            ['provinsi_kode' => '35', 'kode' => '01', 'nama' => 'Kabupaten Pacitan'],
            ['provinsi_kode' => '35', 'kode' => '02', 'nama' => 'Kabupaten Ponorogo'],
            ['provinsi_kode' => '35', 'kode' => '03', 'nama' => 'Kabupaten Trenggalek'],
            ['provinsi_kode' => '35', 'kode' => '04', 'nama' => 'Kabupaten Tulungagung'],
            ['provinsi_kode' => '35', 'kode' => '05', 'nama' => 'Kabupaten Blitar'],
            ['provinsi_kode' => '35', 'kode' => '06', 'nama' => 'Kabupaten Kediri'],
            ['provinsi_kode' => '35', 'kode' => '07', 'nama' => 'Kabupaten Malang'],
            ['provinsi_kode' => '35', 'kode' => '08', 'nama' => 'Kabupaten Lumajang'],
            ['provinsi_kode' => '35', 'kode' => '09', 'nama' => 'Kabupaten Jember'],
            ['provinsi_kode' => '35', 'kode' => '10', 'nama' => 'Kabupaten Banyuwangi'],
            ['provinsi_kode' => '35', 'kode' => '11', 'nama' => 'Kabupaten Bondowoso'],
            ['provinsi_kode' => '35', 'kode' => '12', 'nama' => 'Kabupaten Situbondo'],
            ['provinsi_kode' => '35', 'kode' => '13', 'nama' => 'Kabupaten Probolinggo'],
            ['provinsi_kode' => '35', 'kode' => '14', 'nama' => 'Kabupaten Pasuruan'],
            ['provinsi_kode' => '35', 'kode' => '15', 'nama' => 'Kabupaten Sidoarjo'],
            ['provinsi_kode' => '35', 'kode' => '16', 'nama' => 'Kabupaten Mojokerto'],
            ['provinsi_kode' => '35', 'kode' => '17', 'nama' => 'Kabupaten Jombang'],
            ['provinsi_kode' => '35', 'kode' => '18', 'nama' => 'Kabupaten Nganjuk'],
            ['provinsi_kode' => '35', 'kode' => '19', 'nama' => 'Kabupaten Madiun'],
            ['provinsi_kode' => '35', 'kode' => '20', 'nama' => 'Kabupaten Magetan'],
            ['provinsi_kode' => '35', 'kode' => '21', 'nama' => 'Kabupaten Ngawi'],
            ['provinsi_kode' => '35', 'kode' => '22', 'nama' => 'Kabupaten Bojonegoro'],
            ['provinsi_kode' => '35', 'kode' => '23', 'nama' => 'Kabupaten Tuban'],
            ['provinsi_kode' => '35', 'kode' => '24', 'nama' => 'Kabupaten Lamongan'],
            ['provinsi_kode' => '35', 'kode' => '25', 'nama' => 'Kabupaten Gresik'],
            ['provinsi_kode' => '35', 'kode' => '26', 'nama' => 'Kabupaten Bangkalan'],
            ['provinsi_kode' => '35', 'kode' => '27', 'nama' => 'Kabupaten Sampang'],
            ['provinsi_kode' => '35', 'kode' => '28', 'nama' => 'Kabupaten Pamekasan'],
            ['provinsi_kode' => '35', 'kode' => '29', 'nama' => 'Kabupaten Sumenep'],
            ['provinsi_kode' => '35', 'kode' => '71', 'nama' => 'Kota Kediri'],
            ['provinsi_kode' => '35', 'kode' => '72', 'nama' => 'Kota Blitar'],
            ['provinsi_kode' => '35', 'kode' => '73', 'nama' => 'Kota Malang'],
            ['provinsi_kode' => '35', 'kode' => '74', 'nama' => 'Kota Probolinggo'],
            ['provinsi_kode' => '35', 'kode' => '75', 'nama' => 'Kota Pasuruan'],
            ['provinsi_kode' => '35', 'kode' => '76', 'nama' => 'Kota Mojokerto'],
            ['provinsi_kode' => '35', 'kode' => '77', 'nama' => 'Kota Madiun'],
            ['provinsi_kode' => '35', 'kode' => '78', 'nama' => 'Kota Surabaya'],
            ['provinsi_kode' => '35', 'kode' => '79', 'nama' => 'Kota Batu'],
            ['provinsi_kode' => '36', 'kode' => '01', 'nama' => 'Kabupaten Pandeglang'],
            ['provinsi_kode' => '36', 'kode' => '02', 'nama' => 'Kabupaten Lebak'],
            ['provinsi_kode' => '36', 'kode' => '03', 'nama' => 'Kabupaten Tangerang'],
            ['provinsi_kode' => '36', 'kode' => '04', 'nama' => 'Kabupaten Serang'],
            ['provinsi_kode' => '36', 'kode' => '71', 'nama' => 'Kota Tangerang'],
            ['provinsi_kode' => '36', 'kode' => '72', 'nama' => 'Kota Cilegon'],
            ['provinsi_kode' => '36', 'kode' => '73', 'nama' => 'Kota Serang'],
            ['provinsi_kode' => '36', 'kode' => '74', 'nama' => 'Kota Tangerang Selatan'],
            ['provinsi_kode' => '51', 'kode' => '01', 'nama' => 'Kabupaten Jembrana'],
            ['provinsi_kode' => '51', 'kode' => '02', 'nama' => 'Kabupaten Tabanan'],
            ['provinsi_kode' => '51', 'kode' => '03', 'nama' => 'Kabupaten Badung'],
            ['provinsi_kode' => '51', 'kode' => '04', 'nama' => 'Kabupaten Gianyar'],
            ['provinsi_kode' => '51', 'kode' => '05', 'nama' => 'Kabupaten Klungkung'],
            ['provinsi_kode' => '51', 'kode' => '06', 'nama' => 'Kabupaten Bangli'],
            ['provinsi_kode' => '51', 'kode' => '07', 'nama' => 'Kabupaten Karangasem'],
            ['provinsi_kode' => '51', 'kode' => '08', 'nama' => 'Kabupaten Buleleng'],
            ['provinsi_kode' => '51', 'kode' => '71', 'nama' => 'Kota Denpasar'],
            ['provinsi_kode' => '52', 'kode' => '01', 'nama' => 'Kabupaten Lombok Barat'],
            ['provinsi_kode' => '52', 'kode' => '02', 'nama' => 'Kabupaten Lombok Tengah'],
            ['provinsi_kode' => '52', 'kode' => '03', 'nama' => 'Kabupaten Lombok Timur'],
            ['provinsi_kode' => '52', 'kode' => '04', 'nama' => 'Kabupaten Sumbawa'],
            ['provinsi_kode' => '52', 'kode' => '05', 'nama' => 'Kabupaten Dompu'],
            ['provinsi_kode' => '52', 'kode' => '06', 'nama' => 'Kabupaten Bima'],
            ['provinsi_kode' => '52', 'kode' => '07', 'nama' => 'Kabupaten Sumbawa Barat'],
            ['provinsi_kode' => '52', 'kode' => '08', 'nama' => 'Kabupaten Lombok Utara'],
            ['provinsi_kode' => '52', 'kode' => '71', 'nama' => 'Kota Mataram'],
            ['provinsi_kode' => '52', 'kode' => '72', 'nama' => 'Kota Bima'],
            ['provinsi_kode' => '53', 'kode' => '01', 'nama' => 'Kabupaten Kupang'],
            ['provinsi_kode' => '53', 'kode' => '02', 'nama' => 'Kab Timor Tengah Selatan'],
            ['provinsi_kode' => '53', 'kode' => '03', 'nama' => 'Kabupaten Timor Tengah Utara'],
            ['provinsi_kode' => '53', 'kode' => '04', 'nama' => 'Kabupaten Belu'],
            ['provinsi_kode' => '53', 'kode' => '05', 'nama' => 'Kabupaten Alor'],
            ['provinsi_kode' => '53', 'kode' => '06', 'nama' => 'Kabupaten Flores Timur'],
            ['provinsi_kode' => '53', 'kode' => '07', 'nama' => 'Kabupaten Sikka'],
            ['provinsi_kode' => '53', 'kode' => '08', 'nama' => 'Kabupaten Ende'],
            ['provinsi_kode' => '53', 'kode' => '09', 'nama' => 'Kabupaten Ngada'],
            ['provinsi_kode' => '53', 'kode' => '10', 'nama' => 'Kabupaten Manggarai'],
            ['provinsi_kode' => '53', 'kode' => '11', 'nama' => 'Kabupaten Sumba Timur'],
            ['provinsi_kode' => '53', 'kode' => '12', 'nama' => 'Kabupaten Sumba Barat'],
            ['provinsi_kode' => '53', 'kode' => '13', 'nama' => 'Kabupaten Lembata'],
            ['provinsi_kode' => '53', 'kode' => '14', 'nama' => 'Kabupaten Rote Ndao'],
            ['provinsi_kode' => '53', 'kode' => '15', 'nama' => 'Kabupaten Manggarai Barat'],
            ['provinsi_kode' => '53', 'kode' => '16', 'nama' => 'Kabupaten Nagekeo'],
            ['provinsi_kode' => '53', 'kode' => '17', 'nama' => 'Kabupaten Sumba Tengah'],
            ['provinsi_kode' => '53', 'kode' => '18', 'nama' => 'Kabupaten Sumba Barat Daya'],
            ['provinsi_kode' => '53', 'kode' => '19', 'nama' => 'Kabupaten Manggarai Timur'],
            ['provinsi_kode' => '53', 'kode' => '20', 'nama' => 'Kabupaten Sabu Raijua'],
            ['provinsi_kode' => '53', 'kode' => '21', 'nama' => 'Kabupaten Malaka'],
            ['provinsi_kode' => '53', 'kode' => '71', 'nama' => 'Kota Kupang'],
            ['provinsi_kode' => '61', 'kode' => '01', 'nama' => 'Kabupaten Sambas'],
            ['provinsi_kode' => '61', 'kode' => '02', 'nama' => 'Kabupaten Mempawah'],
            ['provinsi_kode' => '61', 'kode' => '03', 'nama' => 'Kabupaten Sanggau'],
            ['provinsi_kode' => '61', 'kode' => '04', 'nama' => 'Kabupaten Ketapang'],
            ['provinsi_kode' => '61', 'kode' => '05', 'nama' => 'Kabupaten Sintang'],
            ['provinsi_kode' => '61', 'kode' => '06', 'nama' => 'Kabupaten Kapuas Hulu'],
            ['provinsi_kode' => '61', 'kode' => '07', 'nama' => 'Kabupaten Bengkayang'],
            ['provinsi_kode' => '61', 'kode' => '08', 'nama' => 'Kabupaten Landak'],
            ['provinsi_kode' => '61', 'kode' => '09', 'nama' => 'Kabupaten Sekadau'],
            ['provinsi_kode' => '61', 'kode' => '10', 'nama' => 'Kabupaten Melawi'],
            ['provinsi_kode' => '61', 'kode' => '11', 'nama' => 'Kabupaten Kayong Utara'],
            ['provinsi_kode' => '61', 'kode' => '12', 'nama' => 'Kabupaten Kubu Raya'],
            ['provinsi_kode' => '61', 'kode' => '71', 'nama' => 'Kota Pontianak'],
            ['provinsi_kode' => '61', 'kode' => '72', 'nama' => 'Kota Singkawang'],
            ['provinsi_kode' => '62', 'kode' => '01', 'nama' => 'Kabupaten Kotawaringin Barat'],
            ['provinsi_kode' => '62', 'kode' => '02', 'nama' => 'Kabupaten Kotawaringin Timur'],
            ['provinsi_kode' => '62', 'kode' => '03', 'nama' => 'Kabupaten Kapuas'],
            ['provinsi_kode' => '62', 'kode' => '04', 'nama' => 'Kabupaten Barito Selatan'],
            ['provinsi_kode' => '62', 'kode' => '05', 'nama' => 'Kabupaten Barito Utara'],
            ['provinsi_kode' => '62', 'kode' => '06', 'nama' => 'Kabupaten Katingan'],
            ['provinsi_kode' => '62', 'kode' => '07', 'nama' => 'Kabupaten Seruyan'],
            ['provinsi_kode' => '62', 'kode' => '08', 'nama' => 'Kabupaten Sukamara'],
            ['provinsi_kode' => '62', 'kode' => '09', 'nama' => 'Kabupaten Lamandau'],
            ['provinsi_kode' => '62', 'kode' => '10', 'nama' => 'Kabupaten Gunung Mas'],
            ['provinsi_kode' => '62', 'kode' => '11', 'nama' => 'Kabupaten Pulang Pisau'],
            ['provinsi_kode' => '62', 'kode' => '12', 'nama' => 'Kabupaten Murung Raya'],
            ['provinsi_kode' => '62', 'kode' => '13', 'nama' => 'Kabupaten Barito Timur'],
            ['provinsi_kode' => '62', 'kode' => '71', 'nama' => 'Kota Palangkaraya'],
            ['provinsi_kode' => '63', 'kode' => '01', 'nama' => 'Kabupaten Tanah Laut'],
            ['provinsi_kode' => '63', 'kode' => '02', 'nama' => 'Kabupaten Kotabaru'],
            ['provinsi_kode' => '63', 'kode' => '03', 'nama' => 'Kabupaten Banjar'],
            ['provinsi_kode' => '63', 'kode' => '04', 'nama' => 'Kabupaten Barito Kuala'],
            ['provinsi_kode' => '63', 'kode' => '05', 'nama' => 'Kabupaten Tapin'],
            ['provinsi_kode' => '63', 'kode' => '06', 'nama' => 'Kabupaten Hulu Sungai Selatan'],
            ['provinsi_kode' => '63', 'kode' => '07', 'nama' => 'Kabupaten Hulu Sungai Tengah'],
            ['provinsi_kode' => '63', 'kode' => '08', 'nama' => 'Kabupaten Hulu Sungai Utara'],
            ['provinsi_kode' => '63', 'kode' => '09', 'nama' => 'Kabupaten Tabalong'],
            ['provinsi_kode' => '63', 'kode' => '10', 'nama' => 'Kabupaten Tanah Bumbu'],
            ['provinsi_kode' => '63', 'kode' => '11', 'nama' => 'Kabupaten Balangan'],
            ['provinsi_kode' => '63', 'kode' => '71', 'nama' => 'Kota Banjarmasin'],
            ['provinsi_kode' => '63', 'kode' => '72', 'nama' => 'Kota Banjarbaru'],
            ['provinsi_kode' => '64', 'kode' => '01', 'nama' => 'Kabupaten Paser'],
            ['provinsi_kode' => '64', 'kode' => '02', 'nama' => 'Kabupaten Kutai Kartanegara'],
            ['provinsi_kode' => '64', 'kode' => '03', 'nama' => 'Kabupaten Berau'],
            ['provinsi_kode' => '64', 'kode' => '07', 'nama' => 'Kabupaten Kutai Barat'],
            ['provinsi_kode' => '64', 'kode' => '08', 'nama' => 'Kabupaten Kutai Timur'],
            ['provinsi_kode' => '64', 'kode' => '09', 'nama' => 'Kabupaten Penajam Paser Utara'],
            ['provinsi_kode' => '64', 'kode' => '11', 'nama' => 'Kabupaten Mahakam Ulu'],
            ['provinsi_kode' => '64', 'kode' => '71', 'nama' => 'Kota Balikpapan'],
            ['provinsi_kode' => '64', 'kode' => '72', 'nama' => 'Kota Samarinda'],
            ['provinsi_kode' => '64', 'kode' => '74', 'nama' => 'Kota Bontang'],
            ['provinsi_kode' => '65', 'kode' => '01', 'nama' => 'Kabupaten Bulungan'],
            ['provinsi_kode' => '65', 'kode' => '02', 'nama' => 'Kabupaten Malinau'],
            ['provinsi_kode' => '65', 'kode' => '03', 'nama' => 'Kabupaten Nunukan'],
            ['provinsi_kode' => '65', 'kode' => '04', 'nama' => 'Kabupaten Tana Tidung'],
            ['provinsi_kode' => '65', 'kode' => '71', 'nama' => 'Kota Tarakan'],
            ['provinsi_kode' => '71', 'kode' => '01', 'nama' => 'Kabupaten Bolaang Mongondow'],
            ['provinsi_kode' => '71', 'kode' => '02', 'nama' => 'Kabupaten Minahasa'],
            ['provinsi_kode' => '71', 'kode' => '03', 'nama' => 'Kabupaten Kepulauan Sangihe'],
            ['provinsi_kode' => '71', 'kode' => '04', 'nama' => 'Kabupaten Kepulauan Talaud'],
            ['provinsi_kode' => '71', 'kode' => '05', 'nama' => 'Kabupaten Minahasa Selatan'],
            ['provinsi_kode' => '71', 'kode' => '06', 'nama' => 'Kabupaten Minahasa Utara'],
            ['provinsi_kode' => '71', 'kode' => '07', 'nama' => 'Kabupaten Minahasa Tenggara'],
            ['provinsi_kode' => '71', 'kode' => '08', 'nama' => 'Kabupaten Bolaang Mongondow Utara'],
            ['provinsi_kode' => '71', 'kode' => '09', 'nama' => 'Kabupaten Kep. Siau Tagulandang Biaro'],
            ['provinsi_kode' => '71', 'kode' => '10', 'nama' => 'Kabupaten Bolaang Mongondow Timur'],
            ['provinsi_kode' => '71', 'kode' => '11', 'nama' => 'Kabupaten Bolaang Mongondow Selatan'],
            ['provinsi_kode' => '71', 'kode' => '71', 'nama' => 'Kota Manado'],
            ['provinsi_kode' => '71', 'kode' => '72', 'nama' => 'Kota Bitung'],
            ['provinsi_kode' => '71', 'kode' => '73', 'nama' => 'Kota Tomohon'],
            ['provinsi_kode' => '71', 'kode' => '74', 'nama' => 'Kota Kotamobagu'],
            ['provinsi_kode' => '72', 'kode' => '01', 'nama' => 'Kabupaten Banggai'],
            ['provinsi_kode' => '72', 'kode' => '02', 'nama' => 'Kabupaten Poso'],
            ['provinsi_kode' => '72', 'kode' => '03', 'nama' => 'Kabupaten Donggala'],
            ['provinsi_kode' => '72', 'kode' => '04', 'nama' => 'Kabupaten Toli-Toli'],
            ['provinsi_kode' => '72', 'kode' => '05', 'nama' => 'Kabupaten Buol'],
            ['provinsi_kode' => '72', 'kode' => '06', 'nama' => 'Kabupaten Morowali'],
            ['provinsi_kode' => '72', 'kode' => '07', 'nama' => 'Kabupaten Banggai Kepulauan'],
            ['provinsi_kode' => '72', 'kode' => '08', 'nama' => 'Kabupaten Parigi Moutong'],
            ['provinsi_kode' => '72', 'kode' => '09', 'nama' => 'Kabupaten Tojo Una Una'],
            ['provinsi_kode' => '72', 'kode' => '10', 'nama' => 'Kabupaten Sigi'],
            ['provinsi_kode' => '72', 'kode' => '11', 'nama' => 'Kabupaten Banggai Laut'],
            ['provinsi_kode' => '72', 'kode' => '12', 'nama' => 'Kabupaten Morowali Utara'],
            ['provinsi_kode' => '72', 'kode' => '71', 'nama' => 'Kota Palu'],
            ['provinsi_kode' => '73', 'kode' => '01', 'nama' => 'Kabupaten Kepulauan Selayar'],
            ['provinsi_kode' => '73', 'kode' => '02', 'nama' => 'Kabupaten Bulukumba'],
            ['provinsi_kode' => '73', 'kode' => '03', 'nama' => 'Kabupaten Bantaeng'],
            ['provinsi_kode' => '73', 'kode' => '04', 'nama' => 'Kabupaten Jeneponto'],
            ['provinsi_kode' => '73', 'kode' => '05', 'nama' => 'Kabupaten Takalar'],
            ['provinsi_kode' => '73', 'kode' => '06', 'nama' => 'Kabupaten Gowa'],
            ['provinsi_kode' => '73', 'kode' => '07', 'nama' => 'Kabupaten Sinjai'],
            ['provinsi_kode' => '73', 'kode' => '08', 'nama' => 'Kabupaten Bone'],
            ['provinsi_kode' => '73', 'kode' => '09', 'nama' => 'Kabupaten Maros'],
            ['provinsi_kode' => '73', 'kode' => '10', 'nama' => 'Kabupaten Pangkajene dan Kepulauan'],
            ['provinsi_kode' => '73', 'kode' => '11', 'nama' => 'Kabupaten Barru'],
            ['provinsi_kode' => '73', 'kode' => '12', 'nama' => 'Kabupaten Soppeng'],
            ['provinsi_kode' => '73', 'kode' => '13', 'nama' => 'Kabupaten Wajo'],
            ['provinsi_kode' => '73', 'kode' => '14', 'nama' => 'Kabupaten Sidenreng Rappang'],
            ['provinsi_kode' => '73', 'kode' => '15', 'nama' => 'Kabupaten Pinrang'],
            ['provinsi_kode' => '73', 'kode' => '16', 'nama' => 'Kabupaten Enrekang'],
            ['provinsi_kode' => '73', 'kode' => '17', 'nama' => 'Kabupaten Luwu'],
            ['provinsi_kode' => '73', 'kode' => '18', 'nama' => 'Kabupaten Tana Toraja'],
            ['provinsi_kode' => '73', 'kode' => '22', 'nama' => 'Kabupaten Luwu Utara'],
            ['provinsi_kode' => '73', 'kode' => '24', 'nama' => 'Kabupaten Luwu Timur'],
            ['provinsi_kode' => '73', 'kode' => '26', 'nama' => 'Kabupaten Toraja Utara'],
            ['provinsi_kode' => '73', 'kode' => '71', 'nama' => 'Kota Makassar'],
            ['provinsi_kode' => '73', 'kode' => '72', 'nama' => 'Kota Parepare'],
            ['provinsi_kode' => '73', 'kode' => '73', 'nama' => 'Kota Palopo'],
            ['provinsi_kode' => '74', 'kode' => '01', 'nama' => 'Kabupaten Kolaka'],
            ['provinsi_kode' => '74', 'kode' => '02', 'nama' => 'Kabupaten Konawe'],
            ['provinsi_kode' => '74', 'kode' => '03', 'nama' => 'Kabupaten Muna'],
            ['provinsi_kode' => '74', 'kode' => '04', 'nama' => 'Kabupaten Buton'],
            ['provinsi_kode' => '74', 'kode' => '05', 'nama' => 'Kabupaten Konawe Selatan'],
            ['provinsi_kode' => '74', 'kode' => '06', 'nama' => 'Kabupaten Bombana'],
            ['provinsi_kode' => '74', 'kode' => '07', 'nama' => 'Kabupaten Wakatobi'],
            ['provinsi_kode' => '74', 'kode' => '08', 'nama' => 'Kabupaten Kolaka Utara'],
            ['provinsi_kode' => '74', 'kode' => '09', 'nama' => 'Kabupaten Konawe Utara'],
            ['provinsi_kode' => '74', 'kode' => '10', 'nama' => 'Kabupaten Buton Utara'],
            ['provinsi_kode' => '74', 'kode' => '11', 'nama' => 'Kabupaten Kolaka Timur'],
            ['provinsi_kode' => '74', 'kode' => '12', 'nama' => 'Kabupaten Konawe Kepulauan'],
            ['provinsi_kode' => '74', 'kode' => '13', 'nama' => 'Kabupaten Muna Barat'],
            ['provinsi_kode' => '74', 'kode' => '14', 'nama' => 'Kabupaten Buton Tengah'],
            ['provinsi_kode' => '74', 'kode' => '15', 'nama' => 'Kabupaten Buton Selatan'],
            ['provinsi_kode' => '74', 'kode' => '71', 'nama' => 'Kota Kendari'],
            ['provinsi_kode' => '74', 'kode' => '72', 'nama' => 'Kota Bau Bau'],
            ['provinsi_kode' => '75', 'kode' => '01', 'nama' => 'Kabupaten Gorontalo'],
            ['provinsi_kode' => '75', 'kode' => '02', 'nama' => 'Kabupaten Boalemo'],
            ['provinsi_kode' => '75', 'kode' => '03', 'nama' => 'Kabupaten Bone Bolango'],
            ['provinsi_kode' => '75', 'kode' => '04', 'nama' => 'Kabupaten Pohuwato'],
            ['provinsi_kode' => '75', 'kode' => '05', 'nama' => 'Kabupaten Gorontalo Utara'],
            ['provinsi_kode' => '75', 'kode' => '71', 'nama' => 'Kota Gorontalo'],
            ['provinsi_kode' => '76', 'kode' => '01', 'nama' => 'Kabupaten Pasangkayu'],
            ['provinsi_kode' => '76', 'kode' => '02', 'nama' => 'Kabupaten Mamuju'],
            ['provinsi_kode' => '76', 'kode' => '03', 'nama' => 'Kabupaten Mamasa'],
            ['provinsi_kode' => '76', 'kode' => '04', 'nama' => 'Kabupaten Polewali Mandar'],
            ['provinsi_kode' => '76', 'kode' => '05', 'nama' => 'Kabupaten Majene'],
            ['provinsi_kode' => '76', 'kode' => '06', 'nama' => 'Kabupaten Mamuju Tengah'],
            ['provinsi_kode' => '81', 'kode' => '01', 'nama' => 'Kabupaten Maluku Tengah'],
            ['provinsi_kode' => '81', 'kode' => '02', 'nama' => 'Kabupaten Maluku Tenggara'],
            ['provinsi_kode' => '81', 'kode' => '03', 'nama' => 'Kabupaten Kepulauan Tanimbar'],
            ['provinsi_kode' => '81', 'kode' => '04', 'nama' => 'Kabupaten Buru'],
            ['provinsi_kode' => '81', 'kode' => '05', 'nama' => 'Kabupaten Seram Bagian Timur'],
            ['provinsi_kode' => '81', 'kode' => '06', 'nama' => 'Kabupaten Seram Bagian Barat'],
            ['provinsi_kode' => '81', 'kode' => '07', 'nama' => 'Kabupaten Kepulauan Aru'],
            ['provinsi_kode' => '81', 'kode' => '08', 'nama' => 'Kabupaten Maluku Barat Daya'],
            ['provinsi_kode' => '81', 'kode' => '09', 'nama' => 'Kabupaten Buru Selatan'],
            ['provinsi_kode' => '81', 'kode' => '71', 'nama' => 'Kota Ambon'],
            ['provinsi_kode' => '81', 'kode' => '72', 'nama' => 'Kota Tual'],
            ['provinsi_kode' => '82', 'kode' => '01', 'nama' => 'Kabupaten Halmahera Barat'],
            ['provinsi_kode' => '82', 'kode' => '02', 'nama' => 'Kabupaten Halmahera Tengah'],
            ['provinsi_kode' => '82', 'kode' => '03', 'nama' => 'Kabupaten Halmahera Utara'],
            ['provinsi_kode' => '82', 'kode' => '04', 'nama' => 'Kabupaten Halmahera Selatan'],
            ['provinsi_kode' => '82', 'kode' => '05', 'nama' => 'Kabupaten Kepulauan Sula'],
            ['provinsi_kode' => '82', 'kode' => '06', 'nama' => 'Kabupaten Halmahera Timur'],
            ['provinsi_kode' => '82', 'kode' => '07', 'nama' => 'Kabupaten Pulau Morotai'],
            ['provinsi_kode' => '82', 'kode' => '08', 'nama' => 'Kabupaten Pulau Taliabu'],
            ['provinsi_kode' => '82', 'kode' => '71', 'nama' => 'Kota Ternate'],
            ['provinsi_kode' => '82', 'kode' => '72', 'nama' => 'Kota Tidore Kepulauan'],
            ['provinsi_kode' => '91', 'kode' => '03', 'nama' => 'Kabupaten Jayapura'],
            ['provinsi_kode' => '91', 'kode' => '05', 'nama' => 'Kabupaten Kepulauan Yapen'],
            ['provinsi_kode' => '91', 'kode' => '06', 'nama' => 'Kabupaten Biak Numfor'],
            ['provinsi_kode' => '91', 'kode' => '10', 'nama' => 'Kabupaten Sarmi'],
            ['provinsi_kode' => '91', 'kode' => '11', 'nama' => 'Kabupaten Keerom'],
            ['provinsi_kode' => '91', 'kode' => '15', 'nama' => 'Kabupaten Waropen'],
            ['provinsi_kode' => '91', 'kode' => '19', 'nama' => 'Kabupaten Supiori'],
            ['provinsi_kode' => '91', 'kode' => '20', 'nama' => 'Kabupaten Mamberamo Raya'],
            ['provinsi_kode' => '91', 'kode' => '71', 'nama' => 'Kota Jayapura'],
            ['provinsi_kode' => '92', 'kode' => '02', 'nama' => 'Kabupaten Manokwari'],
            ['provinsi_kode' => '92', 'kode' => '03', 'nama' => 'Kabupaten Fak Fak'],
            ['provinsi_kode' => '92', 'kode' => '06', 'nama' => 'Kabupaten Teluk Bintuni'],
            ['provinsi_kode' => '92', 'kode' => '07', 'nama' => 'Kabupaten Teluk Wondama'],
            ['provinsi_kode' => '92', 'kode' => '08', 'nama' => 'Kabupaten Kaimana'],
            ['provinsi_kode' => '92', 'kode' => '11', 'nama' => 'Kabupaten Manokwari Selatan'],
            ['provinsi_kode' => '92', 'kode' => '12', 'nama' => 'Kabupaten Pegunungan Arfak'],
            ['provinsi_kode' => '93', 'kode' => '01', 'nama' => 'Kabupaten Merauke'],
            ['provinsi_kode' => '93', 'kode' => '02', 'nama' => 'Kabupaten Boven Digoel'],
            ['provinsi_kode' => '93', 'kode' => '03', 'nama' => 'Kabupaten Mappi'],
            ['provinsi_kode' => '93', 'kode' => '04', 'nama' => 'Kabupaten Asmat'],
            ['provinsi_kode' => '94', 'kode' => '01', 'nama' => 'Kabupaten Nabire'],
            ['provinsi_kode' => '94', 'kode' => '02', 'nama' => 'Kabupaten Puncak Jaya'],
            ['provinsi_kode' => '94', 'kode' => '03', 'nama' => 'Kabupaten Paniai'],
            ['provinsi_kode' => '94', 'kode' => '04', 'nama' => 'Kabupaten Mimika'],
            ['provinsi_kode' => '94', 'kode' => '05', 'nama' => 'Kabupaten Puncak'],
            ['provinsi_kode' => '94', 'kode' => '06', 'nama' => 'Kabupaten Dogiyai'],
            ['provinsi_kode' => '94', 'kode' => '07', 'nama' => 'Kabupaten Intan Jaya'],
            ['provinsi_kode' => '94', 'kode' => '08', 'nama' => 'Kabupaten Deiyai'],
            ['provinsi_kode' => '95', 'kode' => '01', 'nama' => 'Kabupaten Jayawijaya'],
            ['provinsi_kode' => '95', 'kode' => '02', 'nama' => 'Kab Pegunungan Bintang'],
            ['provinsi_kode' => '95', 'kode' => '03', 'nama' => 'Kabupaten Yahukimo'],
            ['provinsi_kode' => '95', 'kode' => '04', 'nama' => 'Kabupaten Tolikara'],
            ['provinsi_kode' => '95', 'kode' => '05', 'nama' => 'Kabupaten Mamberamo Tengah'],
            ['provinsi_kode' => '95', 'kode' => '06', 'nama' => 'Kabupaten Yalimo'],
            ['provinsi_kode' => '95', 'kode' => '07', 'nama' => 'Kabupaten Lanny Jaya'],
            ['provinsi_kode' => '95', 'kode' => '08', 'nama' => 'Kabupaten Nduga'],
            ['provinsi_kode' => '96', 'kode' => '01', 'nama' => 'Kabupaten Sorong'],
            ['provinsi_kode' => '96', 'kode' => '02', 'nama' => 'Kabupaten Sorong Selatan'],
            ['provinsi_kode' => '96', 'kode' => '03', 'nama' => 'Kabupaten Raja Ampat'],
            ['provinsi_kode' => '96', 'kode' => '04', 'nama' => 'Kabupaten Tambrauw'],
            ['provinsi_kode' => '96', 'kode' => '05', 'nama' => 'Kabupaten Maybrat'],
            ['provinsi_kode' => '96', 'kode' => '71', 'nama' => 'Kota Sorong'],
        ];

        // Add timestamps
        $now = now();
        $data = array_map(function ($item) use ($now) {
            return array_merge($item, [
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $data);

        // Insert in chunks to avoid memory issues if list grows, though this size is fine
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('wilayah_kabupaten')->insert($chunk);
        }
    }
}
